[[redirects]]
  from = "/about"
  to = "/about"
  status = 302

  from = "/portfolio"
  to = "/portfolio"
  status = 302

  from = "/contact"
  to = "/contact"
  status = 302

  from = "/*"
  to = "/index.html"
  status = 200